@startuml
package "order-service" {
    package "order-application" {
        class OrderController {
            - OrderApplicationService orderApplicationService
            + OrderController(OrderApplicationService)
            + createOrder(CreateOrderCommand) : ResponseEntity<CreateOrderResponse>
            + getOrderByTrackingId(UUID) : ResponseEntity<TrackOrderResponse>
        }
    }

    package "order-domain" {
        interface OrderApplicationService {
            + createOrder(CreateOrderCommand) : CreateOrderResponse
            + trackOrder(TrackOrderQuery) : TrackOrderResponse
        }

        class CreateOrderCommand {
            + UUID customerId
            + UUID restaurantId
            + BigDecimal price
            + List<OrderItem> items
            + OrderAddress address
        }

        class CreateOrderResponse {
            + UUID orderTrackingId
            + OrderStatus orderStatus
            + String message
        }

        class TrackOrderQuery {
            + UUID orderTrackingId
        }

        class TrackOrderResponse {
            + UUID orderTrackingId
            + OrderStatus orderStatus
            + List<String> failureMessages
        }
    }
}
@enduml